// automatically generated by the FlatBuffers compiler, do not modify

package com.chatserver.demo.protocols.v1_0;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class NotiName extends Table {
  public static NotiName getRootAsNotiName(ByteBuffer _bb) { return getRootAsNotiName(_bb, new NotiName()); }
  public static NotiName getRootAsNotiName(ByteBuffer _bb, NotiName obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public NotiName __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String nickName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nickNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nickNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createNotiName(FlatBufferBuilder builder,
      int nickNameOffset) {
    builder.startObject(1);
    NotiName.addNickName(builder, nickNameOffset);
    return NotiName.endNotiName(builder);
  }

  public static void startNotiName(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addNickName(FlatBufferBuilder builder, int nickNameOffset) { builder.addOffset(0, nickNameOffset, 0); }
  public static int endNotiName(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

