// automatically generated by the FlatBuffers compiler, do not modify

package com.chatserver.demo.protocols.v1_0;

public final class PacketType {
  private PacketType() { }
  public static final byte HeartBeat = 0;
  public static final byte Login = 1;
  public static final byte Chat = 10;
  public static final byte ReName = 20;
}

